openapi: "3.0.1"
info:
  title: "denner-mobile-v2"
  description: "Denner Mobile Services V2 (for AWL)"
  version: "2021-11-08T08:58:01Z"
servers:
  - url: "https://denner-mobile-api.detailnet.ch/{basePath}"
    variables:
      basePath:
        default: "/v2"
paths:
  /online-filters:
    get:
      parameters:
        - name: "f.types"
          in: "query"
          schema:
            type: "string"
        - name: "Accept-Language"
          in: "header"
          schema:
            type: "string"
        - name: "sort"
          in: "query"
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Cache-Control:
              schema:
                type: "string"
            Vary:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:802555642192:function:${stageVariables.mobile_api}-${stageVariables.lambda_env}_listOnlineFilters:${stageVariables.lambda_alias}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Cache-Control: "stageVariables.cache_control"
              method.response.header.Vary: "'Accept-Language'"
        requestTemplates:
          application/json: "#set($queryParams = $input.params().querystring)\r\n\
            {\r\n  \"version\": \"v2\",\r\n  \"locale\": \"$input.params().header.get('Accept-Language')\"\
            ,\r\n  \"query\": \"#foreach($paramName in $queryParams.keySet())$paramName=$util.escapeJavaScript($queryParams.get($paramName))#if($foreach.hasNext)&#end#end\"\
            \r\n}"
        passthroughBehavior: "when_no_match"
        cacheNamespace: "5mah0t"
        cacheKeyParameters:
          - "method.request.header.Accept-Language"
          - "method.request.querystring.f.types"
          - "method.request.querystring.sort"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /online-filters/{filter_id}/online-groups:
    get:
      parameters:
        - name: "Accept-Language"
          in: "header"
          schema:
            type: "string"
        - name: "filter_id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Cache-Control:
              schema:
                type: "string"
            Vary:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:802555642192:function:${stageVariables.mobile_api}-${stageVariables.lambda_env}_listOnlineGroups:${stageVariables.lambda_alias}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Cache-Control: "stageVariables.cache_control"
              method.response.header.Vary: "'Accept-Language'"
        requestTemplates:
          application/json: "#set($queryParams = $input.params().querystring)\r\n\
            {\r\n  \"version\": \"v2\",\r\n  \"locale\": \"$input.params().header.get('Accept-Language')\"\
            ,\r\n  \"online_filter_id\": \"$input.params().path.get('filter_id')\"\
            ,\r\n  \"query\": \"#foreach($paramName in $queryParams.keySet())$paramName=$util.escapeJavaScript($queryParams.get($paramName))#if($foreach.hasNext)&#end#end\"\
            \r\n}"
        passthroughBehavior: "when_no_match"
        cacheNamespace: "xogyxl"
        cacheKeyParameters:
          - "method.request.header.Accept-Language"
          - "method.request.path.filter_id"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /online-filters/{filter_id}/online-publications:
    get:
      parameters:
        - name: "f.online_group"
          in: "query"
          schema:
            type: "string"
        - name: "Accept-Language"
          in: "header"
          schema:
            type: "string"
        - name: "filter_id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Cache-Control:
              schema:
                type: "string"
            Vary:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:802555642192:function:${stageVariables.mobile_api}-${stageVariables.lambda_env}_listOnlinePublications:${stageVariables.lambda_alias}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Cache-Control: "stageVariables.cache_control"
              method.response.header.Vary: "'Accept-Language'"
        requestTemplates:
          application/json: "#set($queryParams = $input.params().querystring)\r\n\
            {\r\n  \"version\": \"v2\",\r\n  \"locale\": \"$input.params().header.get('Accept-Language')\"\
            ,\r\n  \"query\": \"f.filters=$input.params().path.get('filter_id')&#foreach($paramName\
            \ in $queryParams.keySet())$paramName=$util.escapeJavaScript($queryParams.get($paramName))#if($foreach.hasNext)&#end#end\"\
            \r\n}"
        passthroughBehavior: "when_no_match"
        cacheNamespace: "upft64"
        cacheKeyParameters:
          - "method.request.querystring.f.online_group"
          - "method.request.header.Accept-Language"
          - "method.request.path.filter_id"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /store-filters:
    get:
      parameters:
        - name: "Accept-Language"
          in: "header"
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Cache-Control:
              schema:
                type: "string"
            Vary:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:802555642192:function:${stageVariables.mobile_api}-${stageVariables.lambda_env}_listStoreFilters:${stageVariables.lambda_alias}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Cache-Control: "stageVariables.cache_control"
              method.response.header.Vary: "'Accept-Language'"
        requestTemplates:
          application/json: "#set($queryParams = $input.params().querystring)\r\n\
            {\r\n  \"version\": \"v2\",\r\n  \"locale\": \"$input.params().header.get('Accept-Language')\"\
            \r\n}"
        passthroughBehavior: "when_no_match"
        cacheNamespace: "uu7ssu"
        cacheKeyParameters:
          - "method.request.header.Accept-Language"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /stores:
    get:
      parameters:
        - name: "sort"
          in: "query"
          schema:
            type: "string"
        - name: "page_size"
          in: "query"
          schema:
            type: "string"
        - name: "f.open"
          in: "query"
          schema:
            type: "string"
        - name: "f.channel"
          in: "query"
          schema:
            type: "string"
        - name: "Accept-Language"
          in: "header"
          schema:
            type: "string"
        - name: "page"
          in: "query"
          schema:
            type: "string"
        - name: "f.services"
          in: "query"
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Cache-Control:
              schema:
                type: "string"
            Vary:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:802555642192:function:${stageVariables.mobile_api}-${stageVariables.lambda_env}_listStores:${stageVariables.lambda_alias}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Cache-Control: "stageVariables.cache_control"
              method.response.header.Vary: "'Accept-Language'"
        requestTemplates:
          application/json: "#set($queryParams = $input.params().querystring)\r\n\
            {\r\n  \"version\": \"v2\",\r\n  \"locale\": \"$input.params().header.get('Accept-Language')\"\
            ,\r\n  \"query\": \"#foreach($paramName in $queryParams.keySet())$paramName=$util.escapeJavaScript($queryParams.get($paramName))#if($foreach.hasNext)&#end#end\"\
            \r\n}"
        passthroughBehavior: "when_no_match"
        cacheNamespace: "mqzsio"
        cacheKeyParameters:
          - "method.request.header.Accept-Language"
          - "method.request.querystring.page"
          - "method.request.querystring.page_size"
          - "method.request.querystring.sort"
          - "method.request.querystring.f.services"
          - "method.request.querystring.f.channel"
          - "method.request.querystring.f.open"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /banners:
    get:
      parameters:
        - name: "Accept-Language"
          in: "header"
          schema:
            type: "string"
        - name: "f.platforms"
          in: "query"
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Cache-Control:
              schema:
                type: "string"
            Vary:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:802555642192:function:${stageVariables.banners_api}-${stageVariables.lambda_env}_listBanners:${stageVariables.lambda_alias}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Cache-Control: "stageVariables.cache_control"
              method.response.header.Vary: "'Accept-Language'"
        requestTemplates:
          application/json: "#set($queryParams = $input.params().querystring)\r\n\
            {\r\n  \"version\": \"v2\",\r\n  \"locale\": \"$input.params().header.get('Accept-Language')\"\
            ,\r\n  \"serialization\": {\"group\": \"mobile-listing\"},\r\n  \"query\"\
            : \"f.active=__bool_true&f.display_from=__dtlte_now&f.display_to=__dtgt_now&#foreach($paramName\
            \ in $queryParams.keySet())$paramName=$util.escapeJavaScript($queryParams.get($paramName))#if($foreach.hasNext)&#end#end\"\
            \r\n}"
        passthroughBehavior: "when_no_match"
        cacheNamespace: "3eh9mc"
        cacheKeyParameters:
          - "method.request.header.Accept-Language"
          - "method.request.querystring.f.platforms"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /featured-articles:
    get:
      parameters:
        - name: "Accept-Language"
          in: "header"
          schema:
            type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Cache-Control:
              schema:
                type: "string"
            Vary:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:802555642192:function:${stageVariables.mobile_api}-${stageVariables.lambda_env}_listFeaturedArticles:${stageVariables.lambda_alias}/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Cache-Control: "stageVariables.cache_control"
              method.response.header.Vary: "'Accept-Language'"
        requestTemplates:
          application/json: "#set($queryParams = $input.params().querystring)\r\n\
            {\r\n  \"version\": \"v2\",\r\n  \"locale\": \"$input.params().header.get('Accept-Language')\"\
            ,\r\n  \"query\": \"#foreach($paramName in $queryParams.keySet())$paramName=$util.escapeJavaScript($queryParams.get($paramName))#if($foreach.hasNext)&#end#end\"\
            \r\n}"
        passthroughBehavior: "when_no_match"
        cacheNamespace: "4eqjip"
        cacheKeyParameters:
          - "method.request.header.Accept-Language"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
